language: generic 
sudo: required
services: 
  - docker

before-install:
  - docker build -t inconbeo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true inconbeo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-604235419810"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

