language: generic 
sudo: required
services: 
  - docker

before-install:
  - docker build -t inconbeo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true inconbeo/docker-react npm run test
